code --install-extension ecmel.vscode-html-css
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.code-runner
code --install-extension KevinRose.vsc-python-indent
code --install-extension lonefy.vscode-JS-CSS-HTML-formatter
code --install-extension magicstack.MagicPython
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension samuelcolvin.jinjahtml
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension wholroyd.jinja
